### ISSUE TITLE
About 'self.labeled.data_tensor.clone()' in ImprovedGAN.py

### ISSUE THREAD

**Issue by SpiritBear000** [Sleepychord/ImprovedGAN-pytorch#2]
https://github.com/Sleepychord/ImprovedGAN-pytorch/blob/bc14e80f9cc576222cb07f47ea13e15fd28fcf36/ImprovedGAN.py#L77

when i run ImprovedGAN.py. An error is raised:

AttributeError: 'TensorDataset' object has no attribute 'data_tensor'

how can i solve this probleam?

**Comment by Sleepychord** [comment]
The reason is that your pytorch version is > 0.4. After 0.4, the TensorDataset is modified to support multiple tensors. 
You can change the version to 0.3 or change ".data_tensor" to ". tensors[0]". For details, you can refer to https://pytorch.org/docs/stable/_modules/torch/utils/data/dataset.html#TensorDataset.

**Comment by SpiritBear000** [comment]
Thank you for your reply! The problem have been solved! As you say, just change  ".data_tensor" to ". tensors[0]".The code work! Thank you!
